--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: frontend
    color: green
  name: green-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: frontend
      color: green
  template: 
    metadata: 
      labels: 
        app: frontend
        color: green
      name: green-deploy
    spec: 
      containers: 
        - 
          image: "devopswithcloudhub/python_webpage:green"
          name: green-deploy
          ports: 
            - 
              containerPort: 8080
